#ifndef CONFIG_H
#define CONFIG_H

#define SYS_INIT_LED_STATE 0
#define SYS_INIT_VOLTAGE 12.5f
#define SYS_INIT_CURRENT 1.2f
#define SYS_INIT_TEMPERATURE 35.6f

#define SENSOR_SIM_VOLTAGE 9.5f
#define SENSOR_SIM_CURRENT 2.5f
#define SENSOR_SIM_TEMPERATURE 70.5f

#define SENSOR_NORMAL_VOLTAGE 12.0F
#define SENSOR_NORMAL_CURRENT 1.0f
#define SENSOR_NORMAL_TEMPERATURE 35.0f

#define SENSOR_FAULT_VOLTAGE 9.5f
#define SENSOR_FAULT_CURRENT 2.5F
#define SENSOR_FAULT_TEMPERATURE 75.0f

#define FAULT_LOW_VOLTAGE_TH 10.0f
#define FAULT_OVER_CURRENT_TH 2.0f
#define FAULT_OVER_TEMP_TH 60.0f

#endif
